"""Low-cost challenge domain triage and scanner task contracts."""

from .contracts import (
    CompetitionDomainName,
    DomainSubtype,
    HTTP_WORK_TOOLS,
    NETWORK_WORK_TOOLS,
    PROFILE_FOR_DOMAIN,
    SCANNER_PROFILES,
    SHELL_WORK_TOOLS,
    ScannerContext,
    ScannerProfileName,
    ScannerTaskSpec,
    TaskPhase,
    dependency_batches,
    extract_task_contract,
    profile_for_domain,
)
from .domain import (
    COMPETITION_DOMAINS,
    DomainAssessment,
    ProbeAssessment,
    assess_probe_reports,
    classify_challenge,
)
from .registry import (
    COMPETITION_SCANNER_REGISTRY,
    SCANNER_REGISTRY,
    SKILL_ID_FOR_DOMAIN,
    build_first_round_tasks,
    scanner_for,
    skill_for_domain,
    skill_instructions_for_domain,
)

__all__ = [
    "DomainAssessment",
    "COMPETITION_DOMAINS",
    "COMPETITION_SCANNER_REGISTRY",
    "CompetitionDomainName",
    "DomainSubtype",
    "HTTP_WORK_TOOLS",
    "NETWORK_WORK_TOOLS",
    "PROFILE_FOR_DOMAIN",
    "ProbeAssessment",
    "SCANNER_PROFILES",
    "SCANNER_REGISTRY",
    "SKILL_ID_FOR_DOMAIN",
    "SHELL_WORK_TOOLS",
    "ScannerContext",
    "ScannerProfileName",
    "ScannerTaskSpec",
    "TaskPhase",
    "assess_probe_reports",
    "classify_challenge",
    "build_first_round_tasks",
    "dependency_batches",
    "extract_task_contract",
    "profile_for_domain",
    "scanner_for",
    "skill_for_domain",
    "skill_instructions_for_domain",
]
